### ISSUE TITLE
Selecting cancel during "Set custom cache location" results in a null cache location

### ISSUE THREAD

**Issue by newadventure079** [theophanemayaud/video-simili-duplicate-cleaner#100]
Steps to reproduce:

1. Select Tools -> Set custom cache location
2. On the File browser dialog that is opened, just press cancel

Result:
App console now says `Cache now used:  `

I'm guessing the cache location is now null but I'm not sure

If cancel is chosen, nothing should happen/change

**Comment by theophanemayaud** [comment]
Oh great catch thanks !!!
I’ll check out what it’s actually doing and fix this like you suggested with a proper message.

**Comment by theophanemayaud** [comment]
So indeed, when canceling it was simply setting the path to the cache as null, resulting in the cache being placed in the root of your system !
Thanks a lot, I've fixed if with 791b24cf67123061798a1793059a93f93cf492c5
