### ISSUE TITLE
Create an arm64 build compatible with apple silicon M-series macs

### ISSUE THREAD

**Issue by newadventure079** [theophanemayaud/video-simili-duplicate-cleaner#106]
Right now, the app is x86_64.   `Code Type:             X86-64 (Translated)`

Adding compiling and building steps to create an arm64 build that runs natively on apple silicon macs would be great.

**Comment by theophanemayaud** [comment]
That would be pretty great, I've been wanting to do this as soon as M1 came out. QT is now working with arm, but only on Mac, not windows. As this app is cross platform, I need 1 work machine to be able to build for both windows and macOS. So for now, I'll wait on qt.

**Comment by theophanemayaud** [comment]
I found a way to build as universal app for apple arm and intel machines. This involved building ffmpeg and opencv as universal libraries as well. OpenCV is simple, as it is build with CMake which directly supports a parameter building as universal. ffmep however involves building separately for each architecture (it can still both be done on M1 simply cross building for x86), then using apple command line tools to merge both libraries into a universal library.

Now I need to test if it still works as expected, and performance.

Testing performance (M1 MacBook Air, external SSD): 

File discovery 
- Intel on M1: 75/s (about 9000 files in 2 minutes) Process takes 100% but only on 1 core.
- 

Video processing (without cache)
- Intel on M1:  14/s (3000 in 3min 33s). Process takes all cores to 100%.
- 

Overall time to 1st pair (270GB folder of 12 505 videos)
- Intel on M1: 16min 15s
- 

Intact videos
- Intel on M1: 12 328
- 

Found duplicates
- Intel on M1: 6 557 at 97.1 GB
- 

Recap 
| Step                                  | Intel on M1 | Universal on M1 |
| :----------------              | :------: | :----: |
| File discovery                   |   75/s   | xx |
| Video processing             |   14/s   | xx |
| Overall time to 1st pair    |  16min 15s   | xx |
| Intact videos                     |  12 328    | xx |
| Found duplicates.            |  6 557 at 97.1 GB   | xx |

**Comment by tompalmer** [comment]
Any ETA for completion ?

**Comment by theophanemayaud** [comment]
Hi, happy new year ! 
Sorry for the looong delay. I've just submitted to the apple App Store the new universal binary app build natively now also for arm (M1/M2/M3) with version 1.10.0 that I just !!! It should be out in a few days once apple approves it. I hope you like it and it helps you out :) It's about 30% faster than the rosetta translated version build only for intel x86.
