### ISSUE TITLE
select new cache location does not work on Mac

### ISSUE THREAD

**Issue by Thomasmac** [theophanemayaud/video-simili-duplicate-cleaner#129]
Video Simili uses quite a lot of space for caches. They are useful, though.
In "Tools" one can set a custom cache location. The app indicates in the main window that the location has been changed BUT

a) the cache file remains empty
b) after a new start of the app the selection of the new cache location is ignored. The app uses the default location again

**Comment by theophanemayaud** [comment]
Hey and thanks for reaching out ! As to b) that is indeed a feature I would like to add but haven't gotten to yet.
For a), that is strange. Even after setting a new cache location, and starting a scan, you see the cache.db file remain empty in your newly configured location ?

**Comment by Thomasmac** [comment]
Hi,

thanks for your quick reply.

b) yes, makes sense because this is the whole idea to permanently set the cache file elsewhere in order not to trash the system partition. Otherwise one has to re-set it each time you run Video Simili.

a) yes, cache file is empty, zero bytes. I put the cache file on an external SSD

￼

**Comment by theophanemayaud** [comment]
I'm currently writing the feature to remember the cache location between runs. I took the time to test again how the cache works and it very much still does on my m4 Mac. 

a. Are you sure you've allowed the app access to the location you put the cache ? macOS should ask you if you want to allow, once you've selected the location. 

b. Do you have any error messages in the app ? 

c. And last check, when you enable cache only, does it then not find any duplicates anymore (meaning the cache is indeed empty) ?

**Comment by Thomasmac** [comment]
Hi Theophane,

to answer your questions:

a) VideoSimili has full disk access (to all disks) - checked it in system settings

b) no error message

c) it does find duplicates but it is not generating a cache file. The cache file ist 0 bytes

It does not memorise the selected new cache location either when I re-start the app. It will use the default.

Sanoma 14.6.1, Intel Mac, selected cache file on an external SSD

I can only profit from a cache file when VideoSimili uses the default cache.

Kind regards
Thomas

**Comment by theophanemayaud** [comment]
I just released v1.11.0 which changes a little how caching works. The cache location is now remembered between restarts. And hopefully this fixes the problem of not caching at all, please comment again if not 🤓

**Comment by Thomasmac** [comment]
Hi Théophane,

updated the app. Cache location is not saved after restarting the app. Cache.db Size remains 0.

What’s wrong with my system? Intel iMac on Sequioia 15.01., Cache Set on external SSD. Tried a normal HDD. Does not work either.

Do you want me to delete the app completely using an App Cleaner and re-install it? I just don’t understand why it seems to work on your system. Video Simili has full disk access. What more could I do?

Have you tried to set the cache on an external HDDD?

Best regards
Thomas

**Comment by theophanemayaud** [comment]
Oh no ! Yes I tried multiple scenarios including external disk, and they all work. I'm on arm though, but tested when running through rosetta so it shouldn't make a difference...

Does the default cache location also still not work ? If you navigate to the cache location as indicated by the log message (or just hit "open log folder" as the log files are in the same folder as the default cache location), what size is the cache.db file ?

**Comment by Thomasmac** [comment]
Hi Théophane

I just tested it on my Macbook Air M1 (arm). I installed the new version.

I set the cache file to the download folder on the system SSD. I did a test run. App found vids. Cache.db file size is zero „0“. When re-starting the app the custom location is ignored (not saved).

So, on my iMac (Intel) and on my MacBook Air the custom cache location is ignored and the app does not even generate data in the set Cache-file.

I wonder what you do on your machine to make it work. 

Clean install? 

I mean, this is over my head because my Macbook Air is almost naked - does not have a lot of thrid party software installed that could interfere with your app.

Have your tried on a friend’s Mac?

Regards
Thomas

**Comment by theophanemayaud** [comment]
Good suggestion, but yes I did try on other arm computers, and the cache works. In the default location, or in a new location, it grows.
However there does seem to be a bug with remembering the new cache location, this setting doesn't seem to persist correctly. I'll look for a fix

**Comment by theophanemayaud** [comment]
@Thomasmac is this still an issue for you ? I haven't been able to reproduce and had other reports of the same behavior... So not sure anymore if it was a bug.
Please let me know :)

**Comment by Thomasmac** [comment]
Hi Thephane,

still an issue. I created an „alias“-Link in the default location to the new cache location on my external SSD. The cache grew to 27 kb (before it was empty). It does not grow any more, but there is no new cache file in the default location either. Perhaps I should try a symbolic link instead of a normal alias link. Right now it seems that Video Simili does not create any cache file any longer at all.

Regards
Thomas
