### ISSUE TITLE
Direct contact for custom development

### ISSUE THREAD

**Issue by speedheathenULTRA** [theophanemayaud/video-simili-duplicate-cleaner#15]
@theophanemayaud please contact me, I want to talk to you about an app dev need I have.

jason@speedheathens.com

**Comment by speedheathenULTRA** [comment]
@theophanemayaud It's about developing another app, entirely.

**Comment by theophanemayaud** [comment]
Hey @speedheathenULTRA , I'm very busy at the moment but I'll shoot you an email to chat a bit ! 😉
