### ISSUE TITLE
Windows - default cache location not allowed ?

### ISSUE THREAD

**Issue by theophanemayaud** [theophanemayaud/video-simili-duplicate-cleaner#69]
As per https://github.com/kristiankoskimaki/vidupe/issues/14#issuecomment-1073273079 
Apparently in the Microsoft store published version, there seems to be an issue with cache file write permission. 
The cache works in manual builds, but not when installed via the store.

**Comment by theophanemayaud** [comment]
@lklark in answer to https://github.com/kristiankoskimaki/vidupe/issues/14#issuecomment-1093949438 indeed, I've worked to attempt storing it in the app's dedicated local cache folder. You can now also set a custom location manually, the update should be out in a few days once microsoft approves it !

**Comment by lklark** [comment]
Great! Thanks!

**Comment by theophanemayaud** [comment]
After release in windows store, the default cache location still doesn't seem to work... It's fine because now there's the new feature for the user to select a custom location so they can still use the cache, but it's not great !

**Comment by lklark** [comment]
Thank you Théophane,
but this is fine. I‘ll try that out this evening 😊
