### ISSUE TITLE
Ability to multi highlight in each match group and mark/select files

### ISSUE THREAD

**Issue by hirezz** [theophanemayaud/video-simili-duplicate-cleaner#78]
I keep thinking this is a feature and it's not. But it would be nice to be able to select multiple files within a group using shift+click, which is a feature that already exists, and then a key command that will mark the files you've highlighted to allow you to quickly delete rather than clicking the select box individually for each file.

**Comment by theophanemayaud** [comment]
Hey @hirezz ! Thanks for the suggestion ☺️ I'm not sure I understand however what you mean. 
Would that require a new view ? For now we can only delete one by one, although I would love to add a list view with all the duplicates shown side by side. But I don't understand your request now as this is not yet implemented. Do you have screenshots of where you'd like the sift+click behavior to do something ? What select box are your talking about ?

**Comment by hirezz** [comment]
> Hey @hirezz ! Thanks for the suggestion ☺️ I'm not sure I understand however what you mean. Would that require a new view ? For now we can only delete one by one, although I would love to add a list view with all the duplicates shown side by side. But I don't understand your request now as this is not yet implemented. Do you have screenshots of where you'd like the sift+click behavior to do something ? What select box are your talking about ?

Will try to explain myself better. Sorry about that.

In the screenshot, I chose multiple videos using shift+click. I've added a red box around the checkboxes where you select each video you want to delete. However, it would be nice to be able to delete all of the highlighted videos instead of individually clicking each checkbox
![duplicate](https://user-images.githubusercontent.com/45080149/185208633-162adbe7-3ab2-44a0-a723-82f1ba945090.JPG)
.

**Comment by theophanemayaud** [comment]
Oh @theophanemayaud but that’s not Video simili duplicate cleaner 🙈
I believe you made a mistake and are on the wrong website 😅
