### ISSUE TITLE
Add button to mark as not duplicates

### ISSUE THREAD

**Issue by theophanemayaud** [theophanemayaud/video-simili-duplicate-cleaner#99]
From #98 
> by the way, is there a function to mark both video as "Not A Match"?, so that it wont compare again during next scan?

**Comment by chchia** [comment]
just wonder is there any planned schedule for this function to become available? i can be beta tester if you need one. :)

**Comment by theophanemayaud** [comment]
Hey, sorry no plan as of now, I work on the app whenever I can but it's very hard to predict. Probably in a few months.

**Comment by theophanemayaud** [comment]
I have this figured out, just need to check if the changes don't break anything and I'll publish the change a7d4749518b9ad43018437aed00607ed075faf41

**Comment by theophanemayaud** [comment]
The reads to check if a pair was previously saved as not a duplicate almost doubles the whole scan time... I'm looking to fix that

**Comment by theophanemayaud** [comment]
Hi ! This feature will be released with version 1.10.0 that I just submitted to the apple App Store !!! It should be out in a few days once apple approves it. I hope you like it and it helps you out :)

**Comment by chchia** [comment]
Hi, what about windows user? i am paid windows user and i hope same feature to be available in windows.

**Comment by theophanemayaud** [comment]
Oh right sorry for the oversight. I also submitted to the microsoft App Store, I hope it'll be published soon :)
